version: "3.7"
services:
    client-ci:
        image: mik90/ristretto:client-latest
        network_mode: host
        cap_add:
          - SYS_PTRACE
        volumes:
            # Inclusions:
            - ../:/opt/ristretto
            - ../caches/client_conan_cache:/root/.conan/data
            # Exclusions:
            # Build folder
            - /opt/ristretto/build/
            # This dir
            - /opt/ristretto/docker/
            # server's build caches
            - /opt/ristretto/caches/server_vscode/
            - /opt/ristretto/caches/server_build_cache/
            - /opt/ristretto/caches/server_conan_cache/
    client:
        # For use in development
        entrypoint: ash # Interactive
        image: mik90/ristretto:client-latest
        # CI Wont have this
        devices:
            - "/dev/snd:/dev/snd" # Haven't tested this yet, should be able to get sound input from ALSA
        # Note: If using ports and "run", need to pass in --service-ports
        #ports:
        #    - 5050:5050
        network_mode: host
        cap_add:
          - SYS_PTRACE
        volumes:
            # Inclusions:
            - ../:/opt/ristretto
            - ../caches/client_build_cache:/opt/ristretto/build
            - ../caches/client_conan_cache:/root/.conan/data
            - ../caches/client_vscode:/opt/ristretto/.vscode/
            # Exclusions:
            # This dir
            - /opt/ristretto/docker
            # server's build caches
            - /opt/ristretto/caches/server_vscode/
            - /opt/ristretto/caches/server_build_cache/
            - /opt/ristretto/caches/server_conan_cache/
        build:
            context: .
            dockerfile: ./Client.Dockerfile
    server:
        # Requires a computer with CUDA support
        entrypoint: bash # Interactive
        image: mik90/ristretto:server-latest
        #ports:
        #    - 5051:5051
        network_mode: host
        cap_add:
          - SYS_PTRACE
        volumes:
            # Inclusions:
            - ../:/opt/ristretto
            - ../caches/server_build_cache:/opt/ristretto/build
            - ../caches/server_conan_cache:/root/.conan/data
            - ../caches/server_vscode:/opt/ristretto/.vscode/
            # Exclusions:
            # This dir
            - /opt/ristretto/docker
            # client's build caches
            - /opt/ristretto/caches/client_vscode/
            - /opt/ristretto/caches/client_build_cache/
            - /opt/ristretto/caches/client_conan_cache/
        build:
           # target: grpc-build # useful if not going to run server
            context: .
            dockerfile: ./Server.Dockerfile
