# This is a basic workflow to help you get started with Actions

name: Ristretto CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
             ./caches/client_conan_cache
             ./caches/client_build_cache
             ./caches/server_conan_cache
             ./caches/server_build_cache
        key: ${{ runner.os }}-conan
   
    - name: Pull client image
      working-directory: ./docker
      run: docker-compose pull client-ci
      
    - name: Compile client
      working-directory: ./docker
      run: docker-compose run client-ci -e SKIP_RUN=YES -e SKIP_TESTS=YES --entrypoint "./clientEntry.sh"

# Github actions server doesn't allow usage of /dev/snd, and without /dev/snd, many Alsa functions fail
#    - name: Test client
#      working-directory: ./docker
#      run: docker-compose run client-ci -e SKIP_RUN=YES -e SKIP_BUILD=YES -e SKIP_PROTOC=YES --entrypoint "./clientEntry.sh"

# Server is too big to pull
#    - name: Pull server image
#      working-directory: ./docker
#      run: docker-compose pull server
    
#    - name: Compile server
#      working-directory: ./docker
#      run: docker-compose run server
